name: Publish

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy CMS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/zubry-app
            git restore .
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm install 18.19
            nvm use 18.19
            corepack enable
            cd ~/zubry-app/apps/backend
            pnpm install
            pnpm build
            /lib/node_modules/pm2/bin/pm2 restart CMS

      - name: Deploy Client
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/zubry-app/apps/frontend
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 18.19
            pnpm install
            pnpm build
            /lib/node_modules/pm2/bin/pm2 restart Next

  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://zubry.pl/
            https://zubry.pl/terminarz_2lm
            https://zubry.pl/sklep
          uploadArtifacts: true
          temporaryPublicStorage: true
