name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-cms:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        working-directory: ./apps/backend
        run: npm install

      - name: Test
        working-directory: ./apps/backend
        run: npm run lint

      - name: Build
        working-directory: ./apps/backend
        run: npm run build

  test-client:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        working-directory: ./apps/frontend
        run: npm install

      - name: Test
        working-directory: ./apps/frontend
        run: npm run lint

      - name: Type check
        working-directory: ./apps/frontend
        run: npm exec tsc
